/* Presentation Skills Dashboard Main JavaScript Logic */

// Multi-language Translations Dictionary
const translations = {
  kr: {
    heroTitle: "실무 문서 품질을 구현하는<br><span>AI 프레젠테이션 스킬 대시보드</span>",
    heroSubtitle: "Codex CLI 기반의 검증된 프레젠테이션 워크플로우 컬렉션. 편집 가능한 PPT 슬라이드 deck, 정식 보고서 형식의 Word 문서, 자동 자막/음성 합성 웹 데모 비디오, 고품질 카드뉴스를 3단계 QC 가이드라인으로 완벽하게 제작합니다.",
    btnExploreSkills: "스킬 살펴보기",
    btnViewGallery: "슬라이드 갤러리 감상",
    statSkills: "핵심 파이프라인 스킬",
    statDemos: "검증된 데모 워크스페이스",
    statEditable: "PowerPoint / Word 수정 가능성",
    statQc: "자동 렌더링 & QC 검증",
    skillTag: "Core Capabilities",
    skillTitle: "4가지 핵심 프레젠테이션 스킬",
    skillDesc: "실무 요구사항에 맞춘 맞춤형 워크플로우 스킬을 클릭하여 상세 사양과 렌더링 결과를 확인하세요.",
    galleryTag: "Rendered Evidence",
    galleryTitle: "실제 산출물 슬라이드 갤러리",
    galleryDesc: "AI Agent가 직접 생성하고 LibreOffice / 브라우저로 렌더링 검증을 마친 고품질 산출물 갤러리입니다. 각 카드를 클릭하면 원본 크기로 감상할 수 있습니다.",
    pipelineTag: "Process & Quality Control",
    pipelineTitle: "5단계 품질 관리 (QC) 파이프라인",
    pipelineDesc: "단순 코드 생성을 넘어 실무 오피스 표준에 맞춘 다층 검증 레이어를 거칩니다.",
    promptTag: "Quick Start",
    promptTitle: "30초 설치 및 맞춤 프롬프트 생성기",
    promptDesc: "Codex CLI 환경에 스킬을 설치하고 바로 사용할 수 있는 프롬프트 문구를 자동 생성하세요.",
    promptBuilderTitle: "프롬프트 설정",
    labelSkill: "적용할 스킬 선택",
    labelScenario: "보고서/발표 시나리오",
    catalogTag: "Repositories Demos",
    catalogTitle: "전체 데모 카탈로그",
    catalogDesc: "레포지토리에 포함된 6가지 재현 가능한 실무 예시 카탈로그입니다."
  },
  en: {
    heroTitle: "AI Presentation Skills for<br><span>Real Office Delivery</span>",
    heroSubtitle: "A Codex CLI presentation skill collection covering editable PowerPoint decks, formal Word documents, narrated web demo video synthesis, and Xiaohongshu social cards with multi-layer QC.",
    btnExploreSkills: "Explore Skills",
    btnViewGallery: "View Slide Gallery",
    statSkills: "Packaged Pipeline Skills",
    statDemos: "Reproducible Workspaces",
    statEditable: "Office Editability Rate",
    statQc: "Automated QC Checks",
    skillTag: "Core Capabilities",
    skillTitle: "4 Core Presentation Skills",
    skillDesc: "Click a workflow skill to inspect its technical highlights, tools, and output evidence.",
    galleryTag: "Rendered Evidence",
    galleryTitle: "Rendered Artifact Slide Gallery",
    galleryDesc: "Explore actual PPT slides, DOCX spreads, and XHS cards generated by AI and verified via LibreOffice / browser rendering.",
    pipelineTag: "Process & Quality Control",
    pipelineTitle: "5-Stage QC Pipeline",
    pipelineDesc: "Moving beyond simple code generation to enforce strict multi-layer office typography rules.",
    promptTag: "Quick Start",
    promptTitle: "30-Sec Install & Prompt Generator",
    promptDesc: "Install skills to Codex CLI and generate prompt templates tailored to your use case.",
    promptBuilderTitle: "Prompt Configuration",
    labelSkill: "Select Target Skill",
    labelScenario: "Presentation Scenario",
    catalogTag: "Repositories Demos",
    catalogTitle: "Full Demo Catalog",
    catalogDesc: "6 reproducible office scenarios included in the presentation-skills repository."
  },
  cn: {
    heroTitle: "面向真实办公交付的<br><span>AI 演示文稿 Skills 大屏</span>",
    heroSubtitle: "基于 Codex CLI 的演示工作流 skills 集合，包括商业级可编辑 PPT 协作、正规 Word 文档、网页 demo 配音视频合成及小红书 Markdown 图文卡片。",
    btnExploreSkills: "探索 Skills",
    btnViewGallery: "浏览 Slide 预览",
    statSkills: "核心打包 Skills",
    statDemos: "可复盘 Demo 工作区",
    statEditable: "Office 原生可编辑率",
    statQc: "自动化 QC 质检",
    skillTag: "Core Capabilities",
    skillTitle: "4 大核心演示技能",
    skillDesc: "点击不同 Skill 查看对应的技术亮点、工具链与输出效果。",
    galleryTag: "Rendered Evidence",
    galleryTitle: "真实渲染产物画廊",
    galleryDesc: "查看由 AI Agent 自动生成并经由 LibreOffice / 浏览器渲染质检的 PPT 幻灯片与文档预览。",
    pipelineTag: "Process & Quality Control",
    pipelineTitle: "5 阶段质量控制 (QC) 流程",
    pipelineDesc: "超越简单代码生成，通过严格的多层规范约束模型输出。",
    promptTag: "Quick Start",
    promptTitle: "30 秒安装与 Prompt 生成器",
    promptDesc: "将 Skill 安装至 Codex CLI 并一键生成适合您业务场景的 Prompt。",
    promptBuilderTitle: "Prompt 配置",
    labelSkill: "选择目标 Skill",
    labelScenario: "演示报告场景",
    catalogTag: "Repositories Demos",
    catalogTitle: "完整 Demo 目录",
    catalogDesc: "仓库中包含的 6 个可复盘的真实办公 Demo。"
  }
};

// Skill Suite Detailed Data
const skillData = {
  ppt: {
    title: "ppt-polished-deck-collab",
    tagline: "PowerPoint Presentation Polish & Diagram Collaboration",
    desc: "전략 보고서, 재무 분석, 기술 아키텍처, 키노트 발표에 최적화된 100% 수정 가능한 PPTX 파이프라인. HTML 캡처 이미지를 지양하고, PowerPoint 원생 Shape/Table/Chart를 활용하여 텍스트 넘침, 폰트 표류, 정렬 이탈을 3단계 QC로 검수합니다.",
    features: [
      "python-pptx 기반 100% 수정 가능한 Native 텍스트 box, 도형, 표, 차트 생성",
      "LibreOffice / PDF 자동 변환을 통한 렌더링 미치(Mismatch) 및 텍스트 Overflow 검사",
      "에디토리얼(Ink Style) 대형 타이포그래피 & 연구 보고서(Financial Review) 레이아웃 지원",
      "Source Note, Disclaimer 및 실행 가능한 데이터 파이프라인 캡슐화"
    ],
    tools: ["python-pptx", "matplotlib", "seaborn", "pandas", "LibreOffice", "PDF Preview Engine"],
    previewImg: "presentation-skills-main/assets/apple-editorial-ink-native_contact-sheet.png"
  },
  word: {
    title: "word-polished-doc-collab",
    tagline: "Word Polished Document Collaboration",
    desc: "정밀한 한문/영문 폰트 슬롯 슬롯 페어링(宋体/黑体 + Times New Roman), 1.5배 줄간격, 0.5행 단락 여백, 본문 小四/五号 표 텍스트 규칙을 준수하는 정식 보고서 DOCX 제작 워크플로우.",
    features: [
      "python-docx 및 OOXML 직접 조작을 통한 명확한 한문/영문 폰트 슬롯 지정",
      "표 내부 텍스트 수직 중앙 정렬, 우측 정렬 재무 숫자, 표 제목/그림 캡션 규칙",
      "LibreOffice PDF 변환 및 페이지 렌더링을 통한 양면 Spread / 레이아웃 검수",
      "계약서, 정책 설명서, 연구 보고서 부록, 이사회 제출용 부속 문서에 최적화"
    ],
    tools: ["python-docx", "OOXML Engine", "LibreOffice", "Pandas", "QA Validator"],
    previewImg: "presentation-skills-main/assets/word-refined-industrial-service-transformation_spread.png"
  },
  video: {
    title: "web-demo-video-synthesis",
    tagline: "Web Demo & Voiceover Video Synthesis",
    desc: "제품 시연, 웹 앱 데모, 기술 소개글을 자동으로 나레이션, 브라우저 스크린 녹화, 자막(SRT) 합성하여 고품질 MP4 동영상으로 출력하는 자동화 파이프라인.",
    features: [
      "대사 Script 분할, 세그먼트 TTS 음성 생성 및 정확한 타임라인 테이블(Timing Table) 구축",
      "Playwright 기반 정밀한 브라우저 인터랙션 & 화면 녹화 자동화",
      "ffmpeg을 활용한 음성, 녹화 비디오, 자막(SRT), 배경음악의 모듈식 무손실 합성",
      "숏폼(Xiaohongshu/TikTok 9:16) 및 롱폼(Bilibili/YouTube 16:9) 영역 자동 대응"
    ],
    tools: ["Playwright", "TTS Synthesis", "ffmpeg", "SRT Subtitle Engine", "Node.js"],
    previewImg: "presentation-skills-main/demos/web-demo-video-synthesis-financial-agent/assets/preview_en.png"
  },
  xhs: {
    title: "xhs-markdown-card-collab",
    tagline: "Xiaohongshu Markdown Card Design Collaboration",
    desc: "Markdown 문서 및 아이디어 메모를 모바일 최적화 소셜 미디어 카드(小红书 Image Card)로 자동 변환. YAML Frontmatter 스타일 정의와 브라우저 레이아웃 엔진으로 카드 분량 제어.",
    features: [
      "YAML Front Matter 기반 프레임워크 (테마 색상, 표지 스타일, 타이포그래피 규격)",
      "모바일 반응형 브라우저 레이아웃 기반 가독성 보장 및 텍스트 짤림 QA",
      "구조화된 리서치 노트, 채용 공고, 제품 설명용 PNG 이미지 팩 자동 렌더링",
      "가독성 저하 없는 자동 카드 분량 조절 (Pagination QA)"
    ],
    tools: ["Puppeteer / Playwright", "CSS Grid Layout", "Markdown Parser", "PNG Bundle Exporter"],
    previewImg: "presentation-skills-main/demos/xhs-fictional-grid-storage-research-note/out/post_01.png"
  }
};

// Slide Gallery Items
const galleryData = {
  "apple-editorial": Array.from({ length: 10 }, (_, i) => {
    const num = String(i + 1).padStart(3, '0');
    const titles = [
      "Cover: Apple Editorial Ink Native Test",
      "Executive Agenda & Narrative Pacing",
      "Revenue Structure: iPhone vs Services Engine",
      "Stacked Revenue Composition & Secondary Trend",
      "Hardware Divisions: Mac, iPad & Wearables",
      "Gross Margin Expansion & Capital Returns",
      "Key Thesis & Risk Analysis Matrix",
      "Reproducible SEC 10-K Data Pipeline",
      "Native Shapes & Typography Rules Evidence",
      "Conclusion & Final Hand-off Review Evidence"
    ];
    return {
      src: `presentation-skills-main/demos/apple-editorial-ink-native/build/rendered/ppt_preview/slide_${num}.png`,
      slideNum: `Slide ${i + 1} / 10`,
      title: titles[i] || `Apple Editorial Slide ${i + 1}`
    };
  }),

  "apple-financial": Array.from({ length: 11 }, (_, i) => {
    const num = String(i + 1).padStart(3, '0');
    const titles = [
      "Cover: Apple FY2025 Financial Report Review",
      "Executive Summary & Revenue Drivers",
      "Revenue & Net Income Multi-Year Trend",
      "iPhone Segment Deep Dive & Average Selling Price",
      "Services Division High-Margin Acceleration",
      "Geographic Region Segment Distribution",
      "R&D Spending vs Capital Expenditure Ratio",
      "Balance Sheet Strength & Operating Cash Flow",
      "Valuation Multiples & Peer Benchmarking",
      "Risk Factors & FY2026 Strategic Guidance",
      "Summary & Methodological Appendix"
    ];
    return {
      src: `presentation-skills-main/demos/apple-financial-report-review/build/rendered/ppt_preview/slide_${num}.png`,
      slideNum: `Slide ${i + 1} / 11`,
      title: titles[i] || `Financial Report Slide ${i + 1}`
    };
  }),

  "xhs-cards": Array.from({ length: 4 }, (_, i) => {
    const num = String(i + 1).padStart(2, '0');
    const titles = [
      "XHS Card 1: Grid Energy Storage Research Cover",
      "XHS Card 2: Market Drivers & Capacity Trend",
      "XHS Card 3: Supply Chain & Key Component Analysis",
      "XHS Card 4: Investment Outlook & Summary Notes"
    ];
    return {
      src: `presentation-skills-main/demos/xhs-fictional-grid-storage-research-note/out/post_${num}.png`,
      slideNum: `Card ${i + 1} / 4`,
      title: titles[i]
    };
  }),

  "word-spread": [
    {
      src: "presentation-skills-main/assets/word-refined-industrial-service-transformation_spread.png",
      slideNum: "DOCX Spread View",
      title: "Refined Word Consulting Report Two-Page Spread & QC Layout"
    }
  ]
};

// 5-Stage Pipeline Detail Data
const pipelineSteps = {
  1: {
    title: "1단계: Intent & Briefing (청중 및 의도 분석)",
    desc: "발표 대상(경영진/연구자/투자자), 발표 매체(읽기용 Deck / 읽고 말하기용 Speaker Deck), 슬라이드 장수, 브랜드 템플릿 제약을 확정합니다.",
    checks: ["청중 유형 식별", "페이지 수 가이드라인", "브랜드 슬라이드 마스터 준수"]
  },
  2: {
    title: "2단계: Storyline & Narrative Order (서사 구조 설계)",
    desc: "페이지당 단 하나의 핵심 메시지(One Key Message)를 부여하고, 논리 전개에 필요한 데이터 및 시각 요소 목록을 정리합니다.",
    checks: ["1페이지 1메시지 원칙", "논리적 팩트 구성", "차트/표 캡션 설계"]
  },
  3: {
    title: "3단계: Native Code Execution (코드 실행 생성)",
    desc: "python-pptx 또는 python-docx를 사용하여 HTML 캡처 없이 수정 가능한 Native 텍스트박스, 도형, 표, 원생 Office 차트를 생성합니다.",
    checks: ["Native Office 도형/표 사용", "수정 불가능한 이미지 지양", "폰트 및 줄간격 표준 할당"]
  },
  4: {
    title: "4단계: Preview Render & Export (렌더링 렌더링 변환)",
    desc: "PowerPoint 또는 LibreOffice 헤드리스 모드를 호출하여 실제 PDF 및 슬라이드 이미지로 렌더링을 캡처합니다.",
    checks: ["LibreOffice PDF 변환", "슬라이드 렌더링 캡처", "페이지별 썸네일 검증"]
  },
  5: {
    title: "5단계: 3-Layer QC Enforcement (3단계 품질 검수)",
    desc: "텍스트 영역 이탈(Text Overflow), 요소 겹침(Object Overlap), 폰트 크기 무단 변경(Font Drift), 표 내부 수직 중앙 정렬 미흡을 자동 탐지하여 최종 수정을 거칩니다.",
    checks: ["Text Overflow 탐지", "Object Overlap 검사", "Font Size Drift 방지", "Table Vertical Centering 검사"]
  }
};

// Demo Catalog Data
const catalogDemos = [
  {
    title: "Apple Editorial Ink Native Test",
    skill: "ppt-polished-deck-collab",
    desc: "guizang 스타일 에디토리얼 인크 디자인의 Native PPTX 구현. 대형 세리프 타이틀, 어두운 톤과 밝은 톤의 시각적 리듬감, HTML 캡처 없는 100% 수정 가능한 도형 차트.",
    tools: ["python-pptx", "matplotlib", "LibreOffice"],
    folder: "demos/apple-editorial-ink-native"
  },
  {
    title: "Apple FY2025 Financial Report Review",
    skill: "ppt-polished-deck-collab",
    desc: "정식 중국어 재무 보고서 데크. Native Office 차트, 정교한 표, 데이터 출처 주석, SEC API 연동 재현 가능 파이프라인이 결합된 대표 실무 데모.",
    tools: ["python-pptx", "pandas", "SEC API", "LibreOffice"],
    folder: "demos/apple-financial-report-review"
  },
  {
    title: "Web Demo Video Synthesis (Financial Agent)",
    skill: "web-demo-video-synthesis",
    desc: "금융 AI Agent 시연 웹 애플리케이션의 나레이션, 스크린 녹화, SRT 자막, ffmpeg 무손실 영상 합성 파이프라인.",
    tools: ["Playwright", "TTS API", "ffmpeg", "SRT"],
    folder: "demos/web-demo-video-synthesis-financial-agent"
  },
  {
    title: "Word Refined Industrial Transformation",
    skill: "word-polished-doc-collab",
    desc: "중문/영문 정식 컨설팅 보고서 DOCX. 폰트 슬롯 지정(宋体/Times), 1.5배 줄간격, 캡션 정렬, QA 보고서 포함.",
    tools: ["python-docx", "OOXML Engine", "LibreOffice"],
    folder: "demos/word-refined-industrial-service-transformation"
  },
  {
    title: "Word Lightweight Industrial Brief",
    skill: "word-polished-doc-collab",
    desc: "경영진 브리핑용 경량화 Word 보고서 워크스페이스.",
    tools: ["python-docx", "LibreOffice"],
    folder: "demos/word-lightweight-industrial-operations-brief"
  },
  {
    title: "XHS Fictional Grid Storage Research Note",
    skill: "xhs-markdown-card-collab",
    desc: "Markdown 연구 노트를 모바일 카드뉴스 이미지 팩(PNG)으로 변환하는 샤오홍슈 카드 데모.",
    tools: ["Playwright", "CSS Layout", "Markdown"],
    folder: "demos/xhs-fictional-grid-storage-research-note"
  }
];

// App State
let currentLang = 'kr';
let currentActiveGallery = 'apple-editorial';
let currentModalIndex = 0;

// DOM Elements
document.addEventListener('DOMContentLoaded', () => {
  initLanguage();
  initThemeToggle();
  initSkillTabs();
  initGallery();
  initPipeline();
  initPromptBuilder();
  initCatalog();
  initModal();
});

// 1. Language Initialization
function initLanguage() {
  const langSelect = document.getElementById('langSelect');
  langSelect.addEventListener('change', (e) => {
    currentLang = e.target.value;
    updateLanguageTexts();
  });
}

function updateLanguageTexts() {
  const dict = translations[currentLang];
  if (!dict) return;

  document.getElementById('heroTitle').innerHTML = dict.heroTitle;
  document.getElementById('heroSubtitle').innerText = dict.heroSubtitle;
  document.getElementById('btnExploreSkills').innerText = dict.btnExploreSkills;
  document.getElementById('btnViewGallery').innerText = dict.btnViewGallery;
  document.getElementById('statSkills').innerText = dict.statSkills;
  document.getElementById('statDemos').innerText = dict.statDemos;
  document.getElementById('statEditable').innerText = dict.statEditable;
  document.getElementById('statQc').innerText = dict.statQc;
  document.getElementById('skillTag').innerText = dict.skillTag;
  document.getElementById('skillTitle').innerText = dict.skillTitle;
  document.getElementById('skillDesc').innerText = dict.skillDesc;
  document.getElementById('galleryTag').innerText = dict.galleryTag;
  document.getElementById('galleryTitle').innerText = dict.galleryTitle;
  document.getElementById('galleryDesc').innerText = dict.galleryDesc;
  document.getElementById('pipelineTag').innerText = dict.pipelineTag;
  document.getElementById('pipelineTitle').innerText = dict.pipelineTitle;
  document.getElementById('pipelineDesc').innerText = dict.pipelineDesc;
  document.getElementById('promptTag').innerText = dict.promptTag;
  document.getElementById('promptTitle').innerText = dict.promptTitle;
  document.getElementById('promptDesc').innerText = dict.promptDesc;
  document.getElementById('promptBuilderTitle').innerHTML = `<i class="fa-solid fa-sliders"></i> ${dict.promptBuilderTitle}`;
  document.getElementById('labelSkill').innerText = dict.labelSkill;
  document.getElementById('labelScenario').innerText = dict.labelScenario;
  document.getElementById('catalogTag').innerText = dict.catalogTag;
  document.getElementById('catalogTitle').innerText = dict.catalogTitle;
  document.getElementById('catalogDesc').innerText = dict.catalogDesc;
}

// 2. Theme Toggle
function initThemeToggle() {
  const toggleBtn = document.getElementById('themeToggleBtn');
  const html = document.documentElement;

  toggleBtn.addEventListener('click', () => {
    const currentTheme = html.getAttribute('data-theme');
    const newTheme = currentTheme === 'dark' ? 'light' : 'dark';
    html.setAttribute('data-theme', newTheme);
    toggleBtn.innerHTML = newTheme === 'dark' ? '<i class="fa-solid fa-moon"></i>' : '<i class="fa-solid fa-sun"></i>';
  });
}

// 3. Skill Suite Tabs
function initSkillTabs() {
  const tabs = document.querySelectorAll('#skillTabs .skill-tab');
  tabs.forEach(tab => {
    tab.addEventListener('click', () => {
      tabs.forEach(t => t.classList.remove('active'));
      tab.classList.add('active');
      const skillKey = tab.getAttribute('data-skill');
      renderSkillDetail(skillKey);
    });
  });

  // Render initial tab (PPT)
  renderSkillDetail('ppt');
}

function renderSkillDetail(skillKey) {
  const data = skillData[skillKey];
  const panel = document.getElementById('skillDetailPanel');
  if (!data || !panel) return;

  panel.innerHTML = `
    <div class="skill-info">
      <h3>${data.title}</h3>
      <div class="skill-tagline">${data.tagline}</div>
      <p class="skill-desc">${data.desc}</p>
      
      <ul class="skill-features-list">
        ${data.features.map(f => `<li><i class="fa-solid fa-circle-check"></i> ${f}</li>`).join('')}
      </ul>

      <div class="tools-tag-cloud">
        ${data.tools.map(t => `<span class="tool-chip">${t}</span>`).join('')}
      </div>
    </div>

    <div class="skill-preview-box">
      <img src="${data.previewImg}" alt="${data.title} Preview" class="skill-preview-img">
    </div>
  `;
}

// 4. Slide Gallery & Lightbox
function initGallery() {
  const navBtns = document.querySelectorAll('.gallery-nav .gallery-btn');
  navBtns.forEach(btn => {
    btn.addEventListener('click', () => {
      navBtns.forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      currentActiveGallery = btn.getAttribute('data-gallery');
      renderGalleryGrid(currentActiveGallery);
    });
  });

  renderGalleryGrid('apple-editorial');
}

function renderGalleryGrid(key) {
  const items = galleryData[key] || [];
  const grid = document.getElementById('galleryGrid');
  if (!grid) return;

  grid.innerHTML = items.map((item, idx) => `
    <div class="slide-card glass-panel" onclick="openLightbox(${idx})">
      <img src="${item.src}" alt="${item.title}" loading="lazy">
      <div class="slide-card-info">
        <div class="slide-num">${item.slideNum}</div>
        <div class="slide-title">${item.title}</div>
      </div>
    </div>
  `).join('');
}

// Lightbox Logic
function initModal() {
  const modal = document.getElementById('lightboxModal');
  const closeBtn = document.getElementById('modalCloseBtn');
  const prevBtn = document.getElementById('modalPrevBtn');
  const nextBtn = document.getElementById('modalNextBtn');

  closeBtn.addEventListener('click', closeLightbox);
  modal.addEventListener('click', (e) => {
    if (e.target === modal) closeLightbox();
  });

  prevBtn.addEventListener('click', () => navigateModal(-1));
  nextBtn.addEventListener('click', () => navigateModal(1));

  document.addEventListener('keydown', (e) => {
    if (!modal.classList.contains('open')) return;
    if (e.key === 'Escape') closeLightbox();
    if (e.key === 'ArrowLeft') navigateModal(-1);
    if (e.key === 'ArrowRight') navigateModal(1);
  });
}

function openLightbox(index) {
  currentModalIndex = index;
  updateModalContent();
  document.getElementById('lightboxModal').classList.add('open');
}

function closeLightbox() {
  document.getElementById('lightboxModal').classList.remove('open');
}

function navigateModal(direction) {
  const items = galleryData[currentActiveGallery] || [];
  if (items.length === 0) return;

  currentModalIndex = (currentModalIndex + direction + items.length) % items.length;
  updateModalContent();
}

function updateModalContent() {
  const items = galleryData[currentActiveGallery] || [];
  const item = items[currentModalIndex];
  if (!item) return;

  document.getElementById('modalImg').src = item.src;
  document.getElementById('modalCaption').innerText = `[${item.slideNum}] ${item.title}`;
}

// 5. Workflow Pipeline
function initPipeline() {
  const steps = document.querySelectorAll('#pipelineFlow .pipeline-step');
  steps.forEach(step => {
    step.addEventListener('click', () => {
      steps.forEach(s => s.classList.remove('active'));
      step.classList.add('active');
      const num = step.getAttribute('data-step');
      renderPipelineDetail(num);
    });
  });

  renderPipelineDetail('1');
}

function renderPipelineDetail(stepNum) {
  const detail = pipelineSteps[stepNum];
  const panel = document.getElementById('pipelineDetail');
  if (!detail || !panel) return;

  panel.innerHTML = `
    <h3 style="font-size: 1.3rem; margin-bottom: 8px;">${detail.title}</h3>
    <p style="color: var(--text-secondary); margin-bottom: 16px; font-size: 0.98rem; line-height: 1.6;">${detail.desc}</p>
    <div style="font-weight: 600; font-size: 0.9rem; color: var(--accent-cyan); margin-bottom: 8px;">주요 검증 항목 (QC Rules):</div>
    <ul style="list-style: none; padding-left: 0;">
      ${detail.checks.map(c => `<li style="display: flex; align-items: center; gap: 8px; font-size: 0.9rem; margin-bottom: 6px;"><i class="fa-solid fa-check" style="color: var(--accent-emerald);"></i> ${c}</li>`).join('')}
    </ul>
  `;
}

// 6. Prompt Builder & Copy Commands
function initPromptBuilder() {
  const skillSelect = document.getElementById('promptSkillSelect');
  const scenarioSelect = document.getElementById('promptScenarioSelect');

  skillSelect.addEventListener('change', updatePromptOutput);
  scenarioSelect.addEventListener('change', updatePromptOutput);

  updatePromptOutput();
}

function updatePromptOutput() {
  const skill = document.getElementById('promptSkillSelect').value;
  const scenario = document.getElementById('promptScenarioSelect').value;
  const codeBox = document.getElementById('promptResultCode');

  let promptText = "";

  if (skill === 'ppt-polished-deck-collab') {
    promptText = `Please use the ppt-polished-deck-collab skill to create a formal, editable PowerPoint deck.
Target Topic: ${scenario}
Requirements:
1. Generate native Office PPTX shapes, textboxes, and charts (Do NOT use non-editable HTML screenshots).
2. Organize slide narrative: 1 page = 1 key message with explicit source data notes.
3. Export slide previews using LibreOffice and perform 3-layer QC check (text overflow, font drift, vertical table centering).
4. Deliver the final .pptx file along with rendered PDF previews.`;
  } else if (skill === 'word-polished-doc-collab') {
    promptText = `Please use word-polished-doc-collab skill to create a formal Chinese/English Word report for ${scenario}.
Requirements:
1. Apply Chinese formal-report typography (Songti/Heiti + Times New Roman font pairing).
2. Set body text to 1.5x line spacing, 0.5-line paragraph spacing, and right-aligned financial numbers.
3. Verify table vertical centering and figure captions.
4. Export .docx and review PDF preview.`;
  } else if (skill === 'web-demo-video-synthesis') {
    promptText = `Please use web-demo-video-synthesis to generate a narrated walkthrough video for ${scenario}.
Requirements:
1. Segment narration script into audio clips and build a timing table.
2. Record browser page via Playwright matching segment durations.
3. Mix audio, video, and SRT subtitles using ffmpeg into a publishable MP4.`;
  } else {
    promptText = `Please use xhs-markdown-card-collab to transform this Markdown material into Xiaohongshu social cards for ${scenario}.
Requirements:
1. Use YAML frontmatter for mobile card styling and cover metadata.
2. Run browser layout QA to ensure mobile text readability without overflow.
3. Export high-resolution PNG card bundle.`;
  }

  codeBox.innerText = promptText;
}

function copyInstallCmd() {
  const text = `mkdir -p ~/.codex/skills && unzip presentation-skills-all-skills-*.zip -d ~/.codex/skills`;
  navigator.clipboard.writeText(text).then(() => {
    const copySpan = document.getElementById('copyText1');
    copySpan.innerText = 'Copied!';
    setTimeout(() => copySpan.innerText = 'Copy Command', 2000);
  });
}

function copyPromptCmd() {
  const text = document.getElementById('promptResultCode').innerText;
  navigator.clipboard.writeText(text).then(() => {
    const copySpan = document.getElementById('copyText2');
    copySpan.innerText = 'Copied!';
    setTimeout(() => copySpan.innerText = 'Copy Prompt', 2000);
  });
}

// 7. Demo Catalog & Live Search
function initCatalog() {
  const input = document.getElementById('catalogSearchInput');
  input.addEventListener('input', (e) => {
    const query = e.target.value.toLowerCase();
    renderCatalogGrid(query);
  });

  renderCatalogGrid('');
}

function renderCatalogGrid(query) {
  const grid = document.getElementById('catalogGrid');
  if (!grid) return;

  const filtered = catalogDemos.filter(d => {
    const text = `${d.title} ${d.skill} ${d.desc} ${d.tools.join(' ')}`.toLowerCase();
    return text.includes(query);
  });

  if (filtered.length === 0) {
    grid.innerHTML = `<div style="grid-column: 1/-1; text-align: center; color: var(--text-muted); padding: 40px;">검색 결과가 없습니다.</div>`;
    return;
  }

  grid.innerHTML = filtered.map(d => `
    <div class="catalog-card glass-panel">
      <div>
        <span class="badge badge-blue" style="font-size: 0.72rem; margin-bottom: 8px;">${d.skill}</span>
        <h4>${d.title}</h4>
        <p>${d.desc}</p>
      </div>

      <div>
        <div class="tools-tag-cloud" style="margin-bottom: 12px;">
          ${d.tools.map(t => `<span class="tool-chip">${t}</span>`).join('')}
        </div>
        <div class="catalog-meta">
          <span><i class="fa-regular fa-folder-open"></i> ${d.folder}</span>
          <span style="color: var(--accent-cyan); font-weight: 600;">Reproducible Demo</span>
        </div>
      </div>
    </div>
  `).join('');
}
